# Generated by Django 5.1 on 2024-09-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
