# Generated by Django 5.1 on 2024-09-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0004_cuisine_remove_restaurant_cuisine_restaurant_cuisine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine',
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(default='Unknown Cuisine', max_length=100),
        ),
    ]
