# Generated by Django 5.1.1 on 2024-09-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FoodApp", "0005_remove_restaurant_cuisine_delete_cuisine_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70, unique=True)),
                ("password", models.CharField(default="password", max_length=50)),
            ],
        ),
    ]
