# Generated by Django 5.1 on 2024-09-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0005_remove_restaurant_cuisine_delete_cuisine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='phonenum',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.CharField(default='Unknown Website', max_length=30),
        ),
    ]
