# Generated by Django 5.1.1 on 2024-09-20 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FoodApp", "0006_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="password",
        ),
    ]
