# Generated by Django 5.1 on 2024-09-22 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0007_remove_user_name_remove_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine',
        ),
    ]
